### ISSUE TITLE
lua: not enough memory

### ISSUE THREAD

**Issue by elperepat** [Suxsem/Mqttduino#1]
When using the latest (77c3a59d516de61c0dd3f103d491d6e959a36742), I get a "lua: not enough memory". When using the previous version, it get compiled correctly.

I'm using a ESP8266-01 with NodeMCU 0.9.5 build 20150213.

**Comment by Suxsem** [comment]
Please try file.format(), then reboot, then copy mqtt.lua and init.lua again, then reboot

Let me know :)

**Comment by Suxsem** [comment]
and please update the Arduino sketch to https://github.com/Suxsem/Mqttduino/commit/237c50230142c31037ea8ff155d4548dacd53fc4

**Comment by elperepat** [comment]
Got the latest lua files, file.format() and it worked! Thanks so much! I wanted such a program for the esp8266 since it appeared last fall. Found out about Mqttduino 4 hours after you published it!

I will port the .ino to PIC C (probably mikroC). I'll fork the project tonight and include my .c file in my repo. Would you like pull request for that file?

**Comment by Suxsem** [comment]
Ahah great timing :D
Sure!

**Comment by aryan2013** [comment]
I am getting the same problem 

""NodeMCU 0.9.5 build 20150213  powered by Lua 5.1.4
lua: init.lua:1: not enough memory""

i am following these steps:-

[1.] Flashing firmaware nodemcu_20150213.bin at address 0x00000 using nodemcu-flasher-master 32-bit. Done Successfull.
[2.] Power off and removed GPIO0 GND connection for flash.
[3.] Power ON and connect in Lualoader,
[4.] Upload file init.Lua and mqttduino.lua.
[5.] Power off and then power on.

checked in lualoder and found error "lua: init.lua:1: not enough memory"

**Comment by elperepat** [comment]
I too get the "not enough memory" message when I follow this procedure, Instead, I upload only the mqttduino.lua using lualoader, then type:
  node.compile("mqttduino.lua")
in lualoader. I then type
  file.remove("mqttduino.lua")
to remove the source file.

Finally, I upload a modified version of init.lua containing only:
  dofile("mqttduino.lc")

Using this method, I never got the not enough memory again.

**Comment by aryan2013** [comment]
hi elperepat,
means u first flash nodemcu firmware,
then copy mqttduino.lua

compile manually and then dofile by init.lua...is it?

**Comment by elperepat** [comment]
Yes, that's it! That way, I don't get the "not enough memory" error. You can also try to do a "Format" in lualoader before doing the mqttduino.lua upload. It might help.

**Comment by aryan2013** [comment]
Sorry, i tried now..and failed again....

i am using esp-01 and my heap after loading mqttduino.lua is  node.heap() =17408

Can you tell issue with my flashing?

**Comment by elperepat** [comment]
I'm not at near a esp right now, so I can't tell what the heap is. Which nodemcu firmware did you get? Latest?

**Comment by aryan2013** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11758987/6992740/e0d9ae9a-daf9-11e4-8391-159dcc7cde75.png)

**Comment by aryan2013** [comment]
Hi elperepat,

i am using nodemcu_20150213.bin

**Comment by Suxsem** [comment]
Hi. Have you tried this?https://github.com/Suxsem/Mqttduino/issues/1#issuecomment-76310580

**Comment by Suxsem** [comment]
Sorry this https://github.com/Suxsem/Mqttduino/issues/1#issuecomment-76309011

**Comment by aryan2013** [comment]
Ok after following suxsem hint...i have compiled in elperepat way (manually)....But still doubt ..will it work with arduino sketch???

Suxsem, 

please see file list and coomant execution in lualoader and confirm..will it work...

I have modified init.lua as per elperepat instruction. 

![untitlejd](https://cloud.githubusercontent.com/assets/11758987/6992795/3ea86802-dafc-11e4-958d-93a543e7da60.png)

**Comment by Suxsem** [comment]
It's OK :) have fun

**Comment by aryan2013** [comment]
Ok ...it seems transmitting in every 10 sec(blue led blink)...sometime hangs(blue led blink after 40 sec)... but i am not able to see anything in chrome MQTT client...   what MQTT Client for Laptop ..you are suggesting?

**Comment by Suxsem** [comment]
Mqtt.fx

**Comment by aryan2013** [comment]
I have tested this project successfully,

I want to know .... how to retrive online current date and time in arduino.
I added googleTime.lua and added it in init.lua.But, after execution ..it says "at a time one tcp server allowed" but i want to close one and start other. is it not feasible?

**Comment by Suxsem** [comment]
I solved the problem this way:
I have a script running on my openwrt router that publish the time since epoch every 30 seconds on a mqtt topic. The Arduino client then syncronize its time based on this message. You can find the example in my other repositories (domo-one and domo-openwrt)

**Comment by Jorgen-VikingGod** [comment]
Sorry I have the same problem.
I'm working on mac and upload / format / restart ... with this tool:
https://github.com/kmpm/nodemcu-uploader

To spy and communicate with the ESP8266 (ESP-12)
I'm using the CoolTerm for Mac.

but after restart I get this error too:
<em><strong>NodeMCU 0.9.5 build 20150214  powered by Lua 5.1.4
lua: init.lua:1: not enough memory</strong></em>

Please help me on this.
I also try to format and reupload the files again.
Same error again and again :/
