### ISSUE TITLE
lua: init.lua:1: not enough memory

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [Suxsem/Mqttduino#3]
Sorry I have the same problem.
I'm working on mac and upload / format / restart ... with this tool:
https://github.com/kmpm/nodemcu-uploader

To spy and communicate with the ESP8266 (ESP-12)
I'm using the CoolTerm for Mac.

but after restart I get this error too:
<strong><em>NodeMCU 0.9.5 build 20150214 powered by Lua 5.1.4
lua: init.lua:1: not enough memory</em></strong>

Please help me on this.
I also try to format and reupload the files again.
Same error again and again :/

**Comment by Jorgen-VikingGod** [comment]
Nobody can help here?

**Comment by Suxsem** [comment]
Try the last (integer) version of nodemcu and be sure to properly format the esp8266 (and REBOOT the esp8266 after format) before re upload the files
